name: fernet
description: A Dart library for encrypting and decrypting messages using the Fernet scheme.
version: 0.0.7
repository: https://github.com/elliotwutingfeng/fernet
funding:
  - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - encryption
  - security

environment:
  sdk: ^3.9.0

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.27.0
